# Generated by Django 3.0.7 on 2020-06-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('body', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
