# Generated by Django 3.0.7 on 2020-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_url',
            field=models.URLField(blank=True),
        ),
    ]
