# Generated by Django 3.0.7 on 2020-06-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200629_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_published']},
        ),
    ]
