# Generated by Django 3.0.8 on 2021-02-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_short_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_body',
            new_name='body_short',
        ),
    ]
