# Generated by Django 3.1.7 on 2021-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
